<a href="https://colab.research.google.com/github/Satishap/deep_Leaning_with_pytorch/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')


In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
#matrix
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.4773, -1.3134,  0.2894],
        [ 0.7442,  1.6709,  0.1003]], requires_grad=True)
tensor([-1.3977,  0.1850], requires_grad=True)


In [19]:
#Train DataModel

In [8]:
def model(x):
  return x @ w.t() + b
  

In [9]:
preds=model(inputs)
print(preds)

tensor([[ -42.1065,  170.7705],
        [ -55.0183,  221.3603],
        [-119.0786,  294.6420],
        [   1.5186,  151.6480],
        [ -74.2887,  218.9579]], grad_fn=<AddBackward0>)


In [12]:
#Compare with Targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:
#MSE LOSS
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff * diff) / diff.numel()

In [14]:
#Compute Loss
loss=mse(preds, targets)
print(loss)

tensor(19056.3223, grad_fn=<DivBackward0>)


In [15]:
#Compute Gradient
loss.backward()

In [17]:
print(b)
print(b.grad)

tensor([-1.3977,  0.1850], requires_grad=True)
tensor([-133.9947,  119.4757])


In [16]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.4773, -1.3134,  0.2894],
        [ 0.7442,  1.6709,  0.1003]], requires_grad=True)
tensor([[-10914.8594, -13669.1387,  -7980.0664],
        [ 10192.6152,  10705.8359,   6530.0913]])


In [22]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [24]:
preds=model(inputs)
print(preds)

tensor([[ -42.1065,  170.7705],
        [ -55.0183,  221.3603],
        [-119.0786,  294.6420],
        [   1.5186,  151.6480],
        [ -74.2887,  218.9579]], grad_fn=<AddBackward0>)


In [26]:
loss=mse(preds,targets)
loss

tensor(19056.3223, grad_fn=<DivBackward0>)

In [27]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-10914.8594, -13669.1387,  -7980.0664],
        [ 10192.6152,  10705.8359,   6530.0913]])
tensor([-133.9947,  119.4757])


In [32]:
#Adjust Weights And Reset Gradient
with  torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [33]:
print(w)
print(b)

tensor([[ 0.6956, -1.0400,  0.4490],
        [ 0.5403,  1.4568, -0.0303]], requires_grad=True)
tensor([-1.3950,  0.1826], requires_grad=True)


In [36]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(8692.8789, grad_fn=<DivBackward0>)


In [47]:
#Train For Multiple epochs
for i in range(100):
  preds=model(inputs)
  loss=mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [48]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(162.4745, grad_fn=<DivBackward0>)


In [49]:
preds

tensor([[ 61.3573,  71.8076],
        [ 87.0959,  93.9184],
        [100.8301, 145.9054],
        [ 47.0109,  44.7702],
        [ 95.0190, 102.9016]], grad_fn=<AddBackward0>)

In [50]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])